### ISSUE TITLE
Understanding the output of task1_converter

### ISSUE THREAD

**Issue by pramodith** [adobe-research/deft_corpus#2]
The output of the task1_converter program doesn't seem to be very clean, I see a lot of sentences like " . 178"   "0".  Is this expected, are we supposed to clean such sentences up or am I using the program wrongly? To run the program I use `python task1_converter.py ./data/deft_files/train ./output`

**Comment by sashaspala** [comment]
This is a bug in our script for producing BIO-format .deft files. I am working on a fix and will update shortly.

**Comment by sashaspala** [comment]
The data should now be clean of these tokenization errors. There may still be a few cases where the tokenizer is incorrect (from mistakes in the textbook text or complicated punctuation situations), but these should no longer produce individual "sentences" like you were seeing before.
