### ISSUE TITLE
Double sentences in corpus

### ISSUE THREAD

**Issue by FabijanC** [adobe-research/deft_corpus#24]
I might be missing something, but why do some sentences appear twice in a row in the corpus? E. g. the sentence "_There are usually acknowledgment and reference sections as well as an abstract ( a concise summary ) at the beginning of the paper ._" appears twice in a row in the file data/deft_files/train/t1_biology_0_0.deft.

**Comment by sashaspala** [comment]
The most straightforward way to handle tokens with overlapping tags in the sequence labeling format we are using is to repeat the sentence that contains overlapping tag boundaries. This way we can still maintain the ability for certain tags to overlap each other (imagine a term-definition pair that appears nested within another definition) without creating an entirely new format. Most labeling schemas do not allow for tokens to have multiple tags, but in practice we found that a non-trivial amount of n-grams required more than one label and our goal was to model as close to the true label schema as possible.
