### ISSUE TITLE
Not able to access google group of SemEval2020 Task 6

### ISSUE THREAD

**Issue by mukesh-mehta** [adobe-research/deft_corpus#3]
I am not able to access google groups of SemEval2020 task 6, I also tried to mail on semeval-2020-task-6-organizers@googlegroups.com, but wasn't able to connect. 
Also try to provide alternate contact mail address on CodaLab page.
Please have a look.

Thanks

**Comment by sashaspala** [comment]
Hi, I've updated the group settings so you should be able to email both listservs regardless of group membership now. Please get in touch if you are still having trouble accessing either group.
