### ISSUE TITLE
Missing subtask 3 label: Qualifies/Supplements

### ISSUE THREAD

**Issue by marchbnr** [adobe-research/deft_corpus#39]
The [evaluated labels for subtask 3](https://github.com/adobe-research/deft_corpus/blob/master/evaluation/program/configs/eval_test.yaml#L32) include "Qualifies", but the label is not present in the training data because it is mixed with the "Supplements" label ([as confirmed in the forum](https://groups.google.com/forum/#!topic/semeval-2020-task-6-all/mHzAGnrgdyA)). I just wanted to make sure this is being tracked.

**Comment by sashaspala** [comment]
Yikes, I missed this issue... We'll make sure this is accounted for in the evaluation for subtask 3 - I'll update this first thing tomorrow. For now I've updated the evaluated labels here (766f056ac537ed70e5f903441b6eadce37ca23fb) and on Codalab.
