### ISSUE TITLE
how to construct dataset for Subtask1

### ISSUE THREAD

**Issue by liuyukid** [adobe-research/deft_corpus#4]
Subtask 1: Sentence Classification

Given a sentence, classify whether or not it contains a definition. This is the traditional definition extraction task.

Does this mean that the sentence does not contain a definition only when the tag of each token in a sentence is “O”？

**Comment by sashaspala** [comment]
Use the task1_converter.py script to transform the corpus into the correct format for subtask 1. You will get data in `SENTENCE   HASDEF` format, where HASDEF is either 1 or 0. You can use the original files to determine where exactly the definition appears in the sentence.
