### ISSUE TITLE
Deft and source mismatch

### ISSUE THREAD

**Issue by ashatilov** [adobe-research/deft_corpus#6]
Data mismatch between deft files and corresponding source files: source doesn't represent deft.

For example, in `data/deft_files/dev/t1_biology_0_0.deft`
```
2	data/source_txt/dev/t1_biology_0_0.txt	 0	 1	 O	 -1	 -1	 0
.	data/source_txt/dev/t1_biology_0_0.txt	 1	 2	 O	 -1	 -1	 0

It	data/source_txt/dev/t1_biology_0_0.txt	 3	 5	 O	 -1	 -1	 0
becomes	data/source_txt/dev/t1_biology_0_0.txt	 6	 13	 O	 -1	 -1	 0
```
and in `data/source_txt/dev/t1_biology_0_0.txt`
```
5. Science includes such diverse fields as astronomy, biology, computer sciences, geology, logic, physics, chemistry
```
Also for dev dataset - in the deft folder there are files for which there are no corresponding files in the source folder and vice versa:
`t4_psychology_2_202.deft, t5_economic_2_202.deft, t5_economic_2_303.deft, t7_government_2_101.deft, t7_government_2_202.deft`

`t4_psychology_1_202.txt, t5_economic_1_202.txt, t5_economic_1_303.txt, t7_government_1_101.txt`

**Comment by sashaspala** [comment]
Thanks - This is a bug on our end involving the generation of the plain text source files. I will have a fix out tomorrow.
