### ISSUE TITLE
tokenization errors cause label errors

### ISSUE THREAD

**Issue by sidney1994** [adobe-research/deft_corpus#7]
There are some tokenization errors in your data and tokenization errors cause label errors. for example:
`requickened”—assigned data/source_txt/train/t2_history_2_0.txt 4149 4170 Term T19 0 Direct-Defines`(https://github.com/adobe-research/deft_corpus/blob/be215fecfa4c51e88498e8572e0c29bdb2246c3a/data/deft_files/train/t2_history_2_0.deft#L670)

`money”—an data/source_txt/train/t2_history_1_101.txt 766 775 Term T3 0 Direct-Defines`(https://github.com/adobe-research/deft_corpus/blob/be215fecfa4c51e88498e8572e0c29bdb2246c3a/data/deft_files/train/t2_history_1_101.deft#L142)

`law”—is data/source_txt/train/t6_sociology_2_0.txt 18785 18792 Qualifier T210 T211 Supplements` (https://github.com/adobe-research/deft_corpus/blob/be215fecfa4c51e88498e8572e0c29bdb2246c3a/data/deft_files/train/t6_sociology_2_0.deft#L3319)
Where 'Term ' should be ''I-Term" or "B-Term" and "Qualifier " should be "B-Qualifier" or "I-Qualifier". I found that there are 49 such errors in train. Please fix these bug,  because this bug affects task 2.

**Comment by sashaspala** [comment]
I've fixed quite a few of these tokenization errors, but I did not find 49 of these errors. If they are not fixed in the most recent commit, can you please share the specific list of tokenization errors you found?
