### ISSUE TITLE
What does TAG_ID and ROOT_ID mean

### ISSUE THREAD

**Issue by liuyukid** [adobe-research/deft_corpus#9]
These IDs seem to have no rules to follow.

**Comment by HaotianXue** [comment]
They are unique in pairs for each sentence, I reckon the use of them is to track what defines what.

**Comment by sashaspala** [comment]
TAG_ID and ROOT_ID are used to keep track of the relationships between labeled sequences. Please see [this](https://groups.google.com/forum/#!topic/semeval-2020-task-6-all/3JXZpMikM7M) thread on our Google groups discussion board for the DeftEval task for a more detailed explanation.
